(ns task2)
(def primes
  (lazy-seq (filter (fn [x]
                      (not (some true?
                                 (map (fn [y] (= 0 (mod x y)))
                                      (take-while (fn [y] (<= (* y y) x))
                                                  primes)))))
                    (drop 2 (range)))))

(print (take 100 primes))

;; Unit tests
(require '[clojure.test :refer :all])

(deftest test-primes
  (testing "Primes generated by Sieve of Eratosthenes"
    (is (= (take 5 primes) '(2 3 5 7 11)))
    (is (= (nth primes 100) 547))
    (is (= (nth primes 1000) 7927))
    (is (= (nth primes 10000) 104743))))